CREATE TABLE members (
  id INT NOT NULL AUTO_INCREMENT,
  name_sei VARCHAR(255) NOT NULL,
  name_mei VARCHAR(255) NOT NULL,
  gender INT NOT NULL,
  pref_name VARCHAR(255) NOT NULL,
  address VARCHAR(255) NULL,
  password VARCHAR(255) NOT NULL,
  email VARCHAR(255) NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT '0000-00-00 00:00:00',
  updated_at TIMESTAMP NOT NULL DEFAULT '0000-00-00 00:00:00',
  deleted_at TIMESTAMP NULL,
  PRIMARY KEY (id)
);

CREATE TABLE threads (
    id INT NOT NULL AUTO_INCREMENT,
    member_id INT NOT NULL,
    title VARCHAR(255) NOT NULL,
    content TEXT NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT '0000-00-00 00:00:00',
    updated_at TIMESTAMP NOT NULL DEFAULT '0000-00-00 00:00:00',
    deleted_at TIMESTAMP null ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (id)
);

CREATE TABLE comments (
    id INT NOT NULL AUTO_INCREMENT,
    member_id INT NOT NULL,
    thread_id INT NOT NULL,
    comment TEXT NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT '0000-00-00 00:00:00',
    updated_at TIMESTAMP NOT NULL DEFAULT '0000-00-00 00:00:00',
    deleted_at TIMESTAMP null ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (id)
);

CREATE TABLE likes (
    id INT NOT NULL AUTO_INCREMENT,
    member_id INT NOT NULL,
    comment_id INT NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE administers (
    id INT NOT NULL AUTO_INCREMENT,
    name VARCHAR(255) NOT NULL,
    login_id VARCHAR(255) NOT NULL,
    password VARCHAR(255) NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT '0000-00-00 00:00:00',
    updated_at TIMESTAMP NOT NULL DEFAULT '0000-00-00 00:00:00',
    deleted_at TIMESTAMP null ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (id)
);
